baseURL = 'https://buffbahun-blog.pages.dev/'
locale = 'en-us'
title = 'Buffbahun Blogs'
theme = 'PaperMod'
[params]
mainSections = [
    "computer-architecture",
    "operating-system"
]
disableSpecial1stPost = true
showReadingTime = true
ShowCodeCopyButtons = true
  
[params.footer]
hideCopyright = false

# Core social media profiles section
[[params.socials]]
name = "github"
url = "https://github.com/buffbahun-prog"

[[params.socials]]
name = "email"
url = "mailto:buffbahun@gmail.com"

[[params.socials]]
name = "linkedin"
url = "https://www.linkedin.com/in/asim-sapkota-b903ab227/"