baseURL = 'https://buffbahun-blog.pages.dev/'
locale = 'en-us'
title = 'Buffbahun Blogs'
theme = 'PaperMod'
[params]
mainSections = [
    "computer-architecture",
    "operating-system"
]
disableSpecial1stPost = true
showReadingTime = true